### PR TITLE
Removed trailing namespace comments. #353

### PR DESCRIPTION
**Pull request by DeepakReddyVelagala**
please verify...thanks!!

### CODE REVIEW

**Review by RubyNova — APPROVED** [review]
LGTM

**Comment by RubyNova** [comment]
Hey there @DeepakReddyVelagala, while I have approved the PR, I'll need you to download the git patch file generated from our CI, and apply it to your changes. You can download the file CI has generated from [here](https://github.com/novelrt/NovelRT/suites/3929621983/artifacts/98398111). Thank you for your contribution! :D

**Comment by DeepakReddyVelagala** [comment]
I applied the patch to the forked repo, is there something else I need to do...

**Comment by RubyNova** [comment]
It doesn't appear to have been pushed to your remote. Once it is on your forked repository (on the branch this PR targets) then CI should just run and pass, and then we can merge it for you. :)

**Comment by DeepakReddyVelagala** [comment]
can you please direct me on how to do it

**Comment by RubyNova** [comment]
Well, assuming you have already applied the patch, you should just need to `commit` and then `push`.

**Comment by DeepakReddyVelagala** [comment]
got it...thanks

**Comment by RubyNova** [comment]
Hey, really sorry about this, but I've just realised these commetns are coming from clang-format, not from my editor. I've made a mistake, here.

I need you to modify our `.clang-format` file at the root of the repository, and add the following line:


`FixNamespaceComments: 'false'`

I then need to send you a new git patch file once you've pushed that up. Really sorry about this. I made a mistake in diagnosing the original issue.

**Comment by capnkenny** [comment]
> I'll need you to re-apply your changes to the namespace removals across all the files again after this.

@RubyNova, won't CI push a new git patch to handle this?

**Comment by DeepakReddyVelagala** [comment]
Ohh! do I need to fork your original repo again or should I do it with the repo I already have

**Comment by RubyNova** [comment]
No, the setting only cares about adding them and fixing invalid ones @capnkenny, so the changes will need to be re-applied, which is why I feel bad. :(

@DeepakReddyVelagala no, you can use this existing branch and PR. Thank you for your patience, sorry for the inconvenience.

**Comment by RubyNova** [comment]
Alright, moment of truth... [Here is the new patch file](https://github.com/novelrt/NovelRT/suites/3931179431/artifacts/98426066)

Can you double check it is changing what we expect before committing and pushing please? Thanks for your help.

**Comment by DeepakReddyVelagala** [comment]
Sure.

**Comment by DeepakReddyVelagala** [comment]
I removed few comments after adding FixNamespaceComments: 'false' to clang format file and applied patch and the comments which I deleted did not reappear again does this mean I can proceed with rest of the work...

**Comment by RubyNova** [comment]
Sounds like it worked! Yes you can continue, if it breaks again I will let you know, but fingers crossed it is smooth sailing from here.

**Comment by RubyNova** [comment]
Yes, seems you do, [here it is](https://github.com/novelrt/NovelRT/suites/3931679742/artifacts/98445321), its looking promising from what I've browsed of the git patch file this time.

**Comment by RubyNova** [comment]
clang-format passed. I'm enabling auto-merge. Once CI is done it'll enter our main branch. Thank you again for your contribution! It is very much appreciated. 🎉

**Comment by DeepakReddyVelagala** [comment]
thanks for your guidance and support

**Pull request merged**
